In [5]:
import numpy as np

In [6]:
Nump_Array = np.array([[1,2,3], [4,6,7]])
print(Nump_Array)

[[1 2 3]
 [4 6 7]]


In [7]:
NP1 = np.array([[1,3], [4,5]])
NP2 = np.array([[3,4], [5,7]])

In [14]:
MNP = NP1@NP2
print(MNP)
print()
MNP3 = np.dot(NP1, NP2)
print(MNP3)

[[18 25]
 [37 51]]

[[18 25]
 [37 51]]


In [15]:
MNP2 = NP1*NP2
print(MNP2)
print()
MNP4 = np.multiply(NP1, NP2)
print(MNP4)

[[ 3 12]
 [20 35]]

[[ 3 12]
 [20 35]]
