In [1]:
import numpy as np

In [2]:
Nump_Array = np.array([[1,2,3], [4,6,7]])
print(Nump_Array)

[[1 2 3]
 [4 6 7]]


In [3]:
NP1 = np.array([[1,3], [4,5]])
NP2 = np.array([[3,4], [5,7]])

In [4]:
MNP = NP1@NP2
print(MNP)
print()
MNP3 = np.dot(NP1, NP2)
print(MNP3)

[[18 25]
 [37 51]]

[[18 25]
 [37 51]]


In [6]:
MNP2 = NP1*NP2
print(MNP2)
print()
MNP4 = np.multiply(NP1, NP2)
print(MNP4)

[[ 3 12]
 [20 35]]

[[ 3 12]
 [20 35]]


In [8]:
Sum1 = NP1+NP2

In [10]:
Sub = NP1-NP2

In [11]:
Sub2 =np.subtract(NP1, NP2)

In [13]:
El_Sum = np.sum(NP1)
print(El_Sum)

13


In [14]:
Broad_Nump = NP1+3
print(Broad_Nump)

[[4 6]
 [7 8]]


In [15]:
NP3 = np.array([[3,4]])
NP1+NP3

array([[4, 7],
       [7, 9]])