In [2]:
import numpy as np

In [3]:
Nump_Array = np.array([[1,2,3], [4,6,7]])
print(Nump_Array)

[[1 2 3]
 [4 6 7]]


In [4]:
NP1 = np.array([[1,3], [4,5]])
NP2 = np.array([[3,4], [5,7]])

In [5]:
MNP = NP1@NP2
print(MNP)
print()
MNP3 = np.dot(NP1, NP2)
print(MNP3)

[[18 25]
 [37 51]]

[[18 25]
 [37 51]]


In [6]:
MNP2 = NP1*NP2
print(MNP2)
print()
MNP4 = np.multiply(NP1, NP2)
print(MNP4)

[[ 3 12]
 [20 35]]

[[ 3 12]
 [20 35]]


In [7]:
Sum1 = NP1+NP2

In [8]:
Sub = NP1-NP2

In [9]:
Sub2 =np.subtract(NP1, NP2)

In [10]:
El_Sum = np.sum(NP1)
print(El_Sum)

13


In [11]:
Broad_Nump = NP1+3
print(Broad_Nump)

[[4 6]
 [7 8]]


In [12]:
NP3 = np.array([[3,4]])
NP1+NP3

array([[4, 7],
       [7, 9]])

In [13]:
D = np.divide([12,14,16], 5)
print(D)

[2.4 2.8 3.2]


In [14]:
D = np.floor_divide([12,14,16], 5)
print(D)

[2 2 3]


In [15]:
Sq = np.math.sqrt(10)
print(Sq)

3.1622776601683795


In [16]:
Normal_Distr = np.random.standard_normal((3,4))
print(Normal_Distr)

[[ 1.42275768 -0.1492938  -0.49096271  0.55155289]
 [ 1.63201899 -0.07213112 -0.44940205 -0.34792838]
 [-0.0774922   0.6874255   1.50472481 -1.30524132]]


In [17]:
Uniform_Dist = np.random.uniform(1,12,(3,4))
print(Uniform_Dist)

[[5.61855506 1.04420993 1.37810034 1.62707527]
 [9.42695995 8.06902085 8.08429933 5.37126078]
 [7.60514341 6.37092383 9.23329951 2.21450772]]


In [18]:
# generate float number
np.random.rand()

0.6798967564499482

In [19]:
# generate integer number
Random_ar =np.random.randint(1, 50, (2,5))
print(Random_ar)

[[23 16  8 20 25]
 [12 49 32 14 10]]


In [20]:
Zero = np.zeros((3,4))
print(Zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
Ones = np.ones((3,4))
print(Ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
Filter_Ar = np.logical_and(Random_ar > 30, Random_ar<50)
print(Filter_Ar)

[[False False False False False]
 [False  True  True False False]]


In [24]:
F_Random_Ar = Random_ar[Filter_Ar]
print(F_Random_Ar)


[49 32]
