In [1]:
import numpy as np

In [2]:
Nump_Array = np.array([[1,2,3], [4,6,7]])
print(Nump_Array)

[[1 2 3]
 [4 6 7]]


In [3]:
NP1 = np.array([[1,3], [4,5]])
NP2 = np.array([[3,4], [5,7]])

In [4]:
MNP = NP1@NP2
print(MNP)
print()
MNP3 = np.dot(NP1, NP2)
print(MNP3)

[[18 25]
 [37 51]]

[[18 25]
 [37 51]]


In [5]:
MNP2 = NP1*NP2
print(MNP2)
print()
MNP4 = np.multiply(NP1, NP2)
print(MNP4)

[[ 3 12]
 [20 35]]

[[ 3 12]
 [20 35]]


In [6]:
Sum1 = NP1+NP2

In [7]:
Sub = NP1-NP2

In [8]:
Sub2 =np.subtract(NP1, NP2)

In [9]:
El_Sum = np.sum(NP1)
print(El_Sum)

13


In [10]:
Broad_Nump = NP1+3
print(Broad_Nump)

[[4 6]
 [7 8]]


In [11]:
NP3 = np.array([[3,4]])
NP1+NP3

array([[4, 7],
       [7, 9]])

In [12]:
D = np.divide([12,14,16], 5)
print(D)

[2.4 2.8 3.2]


In [13]:
D = np.floor_divide([12,14,16], 5)
print(D)

[2 2 3]


In [14]:
Sq = np.math.sqrt(10)
print(Sq)

3.1622776601683795


In [15]:
Normal_Distr = np.random.standard_normal((3,4))
print(Normal_Distr)

[[-1.07346927  0.37955431  0.33795974 -1.01116296]
 [-0.15213423  0.17659051 -0.89971183  0.82202589]
 [-0.95501002 -0.68044761  2.3191681  -1.23254955]]


In [16]:
Uniform_Dist = np.random.uniform(1,12,(3,4))
print(Uniform_Dist)

[[ 5.35343757  6.50114098 10.38365592  8.36960503]
 [ 7.81099115  3.79929974  3.89380913  8.61410798]
 [ 8.37897674  5.76523359  2.7524831   6.58387978]]


In [17]:
# generate float number
np.random.rand()

0.010344681852308857

In [18]:
# generate integer number
Random_ar =np.random.randint(1, 50, (2,5))
print(Random_ar)

[[46 24 11 28 12]
 [26 29 44  4  8]]


In [19]:
Zero = np.zeros((3,4))
print(Zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
Ones = np.ones((3,4))
print(Ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
Filter_Ar = np.logical_and(Random_ar > 30, Random_ar<50)
print(Filter_Ar)

[[ True False False False False]
 [False False  True False False]]


In [22]:
F_Random_Ar = Random_ar[Filter_Ar]
print(F_Random_Ar)

[46 44]


In [23]:
Data_N = np.array([1,3,4,5,7,9])
print(Data_N)

[1 3 4 5 7 9]


In [24]:
Mean_N = np.mean(Data_N)
print(Mean_N)

4.833333333333333


In [25]:
Median_N = np.median(Data_N)
print(Median_N)

4.5


In [26]:
Var_N = np.var(Data_N)
print(Var_N)

6.805555555555556


In [27]:
SD_N = np.std(Data_N)
print(SD_N)

2.608745973749755


In [28]:
Nump_Array = np.array([[1,2,3], [4,6,7]])
print(Nump_Array)

[[1 2 3]
 [4 6 7]]


In [29]:
Var_Nump = np.var(Nump_Array, axis=1)
print(Var_Nump)

[0.66666667 1.55555556]


In [30]:
var_Nump2 = np.var(Nump_Array, axis=0)
print(var_Nump2)

[2.25 4.   4.  ]
