# Generate a normal random distribution of order 4 x 5.

In [1]:
import numpy as np

In [3]:
data = np.random.normal(size=(4,5))
print(data)

[[-0.81633946 -0.59455835 -0.40548277 -0.45895448 -2.20185993]
 [-1.24050165 -1.13174489  0.49474444  1.39925256 -0.55068386]
 [-0.06071727  0.22118152 -1.37493157 -2.07839535 -1.59429564]
 [-0.70290863  0.20452127  0.68819471 -1.43985841 -1.04283298]]
