# The Poisson distribution is a discrete probability distribution. This distribution describes how 
# many times a given event can occur at a specified time. The NumPy library allows you to generate 
# random numbers from this distribution with the np.random.poisson() 
# function. Generate a 50 x 3 random shape distribution, with a known number of occurrences equal to 5.

In [1]:
import numpy as np

In [2]:
array = np.random.poisson(lam=5, size=(50, 3))
print(array)

[[ 8  5  6]
 [ 5  2  7]
 [ 5  4  6]
 [ 7  8  8]
 [ 8  6  4]
 [ 5  8  6]
 [ 6  3  6]
 [ 4  2  3]
 [ 6  8  0]
 [ 4  4  4]
 [ 5  2  5]
 [ 3  6  3]
 [ 4  2  8]
 [ 4  6  6]
 [ 3  6  4]
 [ 4  6 10]
 [ 3  9  2]
 [ 5  7  4]
 [ 5  6  7]
 [ 4  3  3]
 [ 7  3  4]
 [ 6  3  4]
 [ 3  3  2]
 [ 5  1  2]
 [ 7  5  5]
 [ 6  3  2]
 [ 3  1  5]
 [ 4  6  6]
 [ 7  4  5]
 [ 4  5  2]
 [ 4  5  3]
 [ 6  4 12]
 [ 3  6  4]
 [ 5  3  4]
 [ 8  3  7]
 [ 6  3  6]
 [ 8  4  6]
 [ 6  3  7]
 [ 6  2  2]
 [ 6  5  6]
 [ 2  2  4]
 [ 2  8  2]
 [ 8  5  3]
 [ 8  4  3]
 [ 3  6  6]
 [ 5  6  9]
 [ 3  5  3]
 [ 5  5  5]
 [ 7  6  4]
 [ 3  4  9]]
