# Generate a 30 x 5 shape array with numbers between 0 and 4.
# Tip: np.random.randint().



In [1]:
import numpy as np

In [3]:
array = np.random.randint(low=0, high=4, size=(30,5))
# array = np.random.randint(5, size=(30,5))
print(array)

[[0 0 0 4 3]
 [0 1 3 2 4]
 [1 3 4 2 0]
 [2 0 0 3 3]
 [0 1 0 2 3]
 [2 3 0 0 2]
 [2 1 4 2 2]
 [3 1 0 2 0]
 [1 3 2 2 1]
 [3 3 2 4 2]
 [2 4 0 4 0]
 [3 2 2 2 0]
 [4 1 0 2 2]
 [0 1 3 2 1]
 [2 1 2 0 2]
 [0 4 1 3 1]
 [3 0 1 3 3]
 [3 3 2 0 4]
 [0 0 4 0 0]
 [1 2 3 0 0]
 [0 1 1 0 3]
 [2 0 0 1 0]
 [2 3 1 1 2]
 [1 2 1 0 0]
 [4 3 0 1 4]
 [3 3 4 3 2]
 [4 4 1 4 2]
 [0 0 1 0 3]
 [2 3 3 3 2]
 [1 1 2 0 4]]
