In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4])

In [3]:
x

array([1, 2, 3, 4])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.random.random(5)

array([0.63051734, 0.52065967, 0.11771214, 0.72700595, 0.3698933 ])