In [1]:
import numpy as np

In [2]:
new_math = np.array([1,2,3])

In [5]:
new_ones = np.ones(3)
print(new_ones)

[1. 1. 1.]


In [4]:
new_math + new_ones

array([2., 3., 4.])

In [6]:
new_math * 2

array([2, 4, 6])

In [7]:
new_ones * 3

array([3., 3., 3.])