In [1]:
import numpy as np

In [2]:
new_math = np.array([1,2,3])

In [3]:
x = np.array([[10,20], [30,40]])

In [4]:
x

array([[10, 20],
       [30, 40]])

In [5]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.random.random((3,4))

array([[0.89427889, 0.76757027, 0.73864164, 0.18025972],
       [0.46939021, 0.12625383, 0.72785877, 0.52007491],
       [0.12200012, 0.57371862, 0.76322387, 0.22963055]])