In [1]:
import numpy as np

In [2]:
y = np.array([[2,4], [5,6]])

In [3]:
x = np.array([[10,20], [30,40]])

In [4]:
x + y

array([[12, 24],
       [35, 46]])

In [5]:
x.dot(y)

array([[120, 160],
       [260, 360]])

In [6]:
y

array([[2, 4],
       [5, 6]])

In [7]:
y.max()

6

In [8]:
y.min()

2