# Define the matrices below using NumPy. Use the np.array() method.

In [1]:
import numpy as np

In [5]:
A = np.array([[1,2,3], [2,1,-1]])
A


array([[ 1,  2,  3],
       [ 2,  1, -1]])

In [6]:

B = np.array([[1,-2,0], [3,0,1], [4,5,6]])
B

array([[ 1, -2,  0],
       [ 3,  0,  1],
       [ 4,  5,  6]])

In [11]:
# C = np.array([[1,2,3], [4,5,6], [7,8,9]])
C = np.array(range(1, 10)).reshape(3,3)
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
D = np.array([1,4,-3]).reshape(-1,1)
D

array([[ 1,  4, -3]])