In [1]:
import numpy as np

In [6]:
A = np.array([[1,-3,2],[2,1,-3],[4,-3,-1]])
B = np.array([[1,0,4],[-7,5,5],[25,9,11]])

print("Before",A)
print("After: ")
print(A.T)
print()
print("Before: ")
print(B)
print("After: ")
print(B.transpose())

Before [[ 1 -3  2]
 [ 2  1 -3]
 [ 4 -3 -1]]
After: 
[[ 1  2  4]
 [-3  1 -3]
 [ 2 -3 -1]]
