In [1]:
import numpy as np

In [4]:
A = np.array([[4,-1,2,-2],[3,-1,0,0],[2,3,1,0],[0,7,1,1]])
r = np.linalg.inv(A)

print(r)

[[ -1.  -1.   4.  -2.]
 [ -3.  -4.  12.  -6.]
 [ 11.  14. -43.  22.]
 [ 10.  14. -41.  21.]]
