# Define the matrices below using NumPy. Use the np.array() method.



In [1]:
import numpy as np

In [3]:
E = np.array(range(1,7)).reshape(-1,1)
E

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [5]:
F = np.array([1,0,3,-10])
F

array([  1,   0,   3, -10])

In [6]:
G = np.array(range(1,6))
G

array([1, 2, 3, 4, 5])