In [2]:
import numpy as np

In [7]:
A = np.zeros(shape=(2,2))
A

array([[0., 0.],
       [0., 0.]])

In [9]:
B = np.zeros(shape=(3,5))
B

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
C = np.ones(shape=(5,5))
C

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
I2 = np.eye(2)
I2

array([[1., 0.],
       [0., 1.]])

In [13]:
I3 = np.eye(3)
I3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
I6 = np.eye(6)
I6

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])