# Define the triangular matrices below using the NumPy. Use the np.triu() and np.tril() methods.



In [1]:
import numpy as np

In [6]:
A = np.triu([[1,2,3], [4,5,6], [7,8,9]], 0)
A

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [7]:
B = np.tril([[1,2,3], [4,5,6], [7,8,9]], 0)
B

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [10]:
C = np.triu(np.arange(100,125).reshape(5,5))
C

array([[100, 101, 102, 103, 104],
       [  0, 106, 107, 108, 109],
       [  0,   0, 112, 113, 114],
       [  0,   0,   0, 118, 119],
       [  0,   0,   0,   0, 124]])