# Define the matrices below using NumPy. Use the np.diag() and np.array() methods.



In [1]:
import numpy as np

In [3]:
A = np.diag([7,1, -1])
A

array([[ 7,  0,  0],
       [ 0,  1,  0],
       [ 0,  0, -1]])

In [9]:
B = np.diag([3]* 4)
B

array([[3, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 3]])

In [5]:
C = np.diag(range(-5,0))
C

array([[-5,  0,  0,  0,  0],
       [ 0, -4,  0,  0,  0],
       [ 0,  0, -3,  0,  0],
       [ 0,  0,  0, -2,  0],
       [ 0,  0,  0,  0, -1]])