In [1]:
import numpy as np

In [24]:
A = np.array([[1,2,3], [2,1,-1]])
B = np.array([[-2,0,1], [3,0,1]])
C = np.array([-1,2,4]).reshape(-1,1)
D = np.array([[2, -1]])

print(f"Sum A B: {A + B}")
print(f"Mult A C: {A.dot(C)}")
print(f"Mult B C: {B.dot(C)}")
print(f"Mult C D: {C.dot(D)}")
print(f"Mult D A: {D.dot(A)}")
print(f"Mult D B: {D.dot(B)}")
print(f"-A: {(-1)*A}")
print(f"-D: {(-1)* D}")
print(f"Mult 2A + 3B: {2*A+3*B}")

Sum A B: [[-1  2  4]
 [ 5  1  0]]
Mult A C: [[15]
 [-4]]
Mult B C: [[6]
 [1]]
Mult C D: [[-2  1]
 [ 4 -2]
 [ 8 -4]]
Mult D A: [[0 3 7]]
Mult D B: [[-7  0  1]]
-A: [[-1 -2 -3]
 [-2 -1  1]]
-D: [[-2  1]]
Mult 2A + 3B: [[-4  4  9]
 [13  2  1]]
