# Create the following arrays:
# array([[10],
# [15],
# [20],
# [25],
# [30],
# [35],
# [40],
# [45]])
# b array([-50, -45, -40, -35, -30, -25, -20, -15, -10,  -5])
# c array([[ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],
# [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
# [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],
# [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],
# [130, 132, 134, 136, 138, 140, 142, 144, 146, 148]])
       

In [1]:
import numpy as np

In [6]:
arrayA = np.arange(10, 50, 5).reshape(-1,1)
arrayB = np.array(range(-50, 0, 5))
arrayC = np.arange(50, 150, 2).reshape(5, 10)

print(f"a - {arrayA}")
print(f"b - {arrayB}")
print(f"c - {arrayC}")

a - [[10]
 [15]
 [20]
 [25]
 [30]
 [35]
 [40]
 [45]]
b - [-50 -45 -40 -35 -30 -25 -20 -15 -10  -5]
c - [[ 50  52  54  56  58  60  62  64  66  68]
 [ 70  72  74  76  78  80  82  84  86  88]
 [ 90  92  94  96  98 100 102 104 106 108]
 [110 112 114 116 118 120 122 124 126 128]
 [130 132 134 136 138 140 142 144 146 148]]
