# Use the np.full(shape, fill_value, dtype) function to create the following arrays. 
# This function allows you to create an array with a user-defined shape and dtype, filled with a certain value.
# a - array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])
# b - array([[-5., -5., -5., -5.],
#    [-5., -5., -5., -5.],
#    [-5., -5., -5., -5.],
#    [-5., -5., -5., -5.]])
# c- array([[3, 3, 3],
#    [3, 3, 3],
#    [3, 3, 3]])
# d - array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
#    [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
#    [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
#    [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
#    [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
#    [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
#    [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
#    [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
#    [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
#    [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])

In [1]:
import numpy as np

In [8]:
arrayA = np.full(shape=(10), fill_value=5, dtype=float)
arrayB = np.full(shape=(4,4), fill_value=-5, dtype=float)
arrayC = np.full(shape=(3,3), fill_value=3)
arrayD = np.full(shape=(10,10), fill_value=50)

print(f"a - {arrayA}")
print(f"b - {arrayB}")
print(f"c - {arrayC}")
print(f"d - {arrayD}")

a - [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
b - [[-5. -5. -5. -5.]
 [-5. -5. -5. -5.]
 [-5. -5. -5. -5.]
 [-5. -5. -5. -5.]]
c - [[3 3 3]
 [3 3 3]
 [3 3 3]]
