# The np.ones() function allows you to create an array filled with the number 1 in all your entries. We can specify as arguments the shape and the kind of dtype of the array. Use this function to create the following arrays:
# a - array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
# b - array([[1., 1., 1., 1.],
#       [1., 1., 1., 1.],
#       [1., 1., 1., 1.],
#       [1., 1., 1., 1.]])
# c - array([[1., 1.],
#       [1., 1.],
#       [1., 1.]])

In [1]:
import numpy as np

In [5]:
arrayA = np.ones(10)
arrayB = np.ones((4,4))
arrayC = np.ones((3,2))

print(f"a - {arrayA}")
print(f"b - {arrayB}")
print(f"c - {arrayC}")

a - [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
b - [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
c - [[1. 1.]
 [1. 1.]
 [1. 1.]]
